version: "3.7"
services:
  app:
    build:
      args:
        user: fredrick
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: trading-point
    container_name: trading-point-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tradingpoint

  db:
    image: mysql:8.0
    container_name: trading-point-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - tradingpoint

  nginx:
    image: nginx:alpine
    container_name: trading-point-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - tradingpoint

networks:
  tradingpoint:
    driver: bridge
